bind 127.0.0.1 ::1
protected-mode yes
port 6379
tcp-backlog 128
timeout 0
tcp-keepalive 60
supervised systemd
daemonize no
databases 1
save ""
appendonly no
maxmemory 128mb
maxmemory-policy allkeys-lru
